### ISSUE TITLE
Reproduction problem

### ISSUE THREAD

**Issue by liwenke1** [DeepSoftwareAnalytics/KADEL#1]
Dear authors:

Thank you for your excellent work! 

I have a question when i train CodeT5 model use `sh/run_KADEL_without_knowledge.py`, there has a error
<img width="1087" alt="image" src="https://github.com/DeepSoftwareAnalytics/KADEL/assets/48514182/a7fa6461-4c8f-4c3e-ad41-9f34fc904c3c">
This may seem like a version incompatibility issue or something else, so how can i solve this problem?

( i configured the environment according to the readme file, except for the installation of transformers, which was not explained in the file, so I installed version 4.38.2 )

**Comment by itaowei** [comment]
Thanks for your attention!
I am sorry that I've been extremely busy lately, but I will make sure to respond to you by next weekend.

**Comment by itaowei** [comment]
Thanks for your patience!

I have added the missing `transformers` modified by us at the commit 9dcf69df5c5e3ccff75f01f6d3ff91afdf5d7f3f .

Our modification is based on the https://github.com/huggingface/transformers/tree/v4.6.1/src/transformers 

Hope this commit can be helpful to you!
